---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME
  labels:
    name: APP_NAME
    project: PROJECT_NAME
    version: 'APP_VERSION'
    app_build: "APP_BUILD"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: APP_NAME
      project: PROJECT_NAME
  template:
    metadata:
      labels:
        name: APP_NAME
        project: PROJECT_NAME
        version: 'APP_VERSION'
        app_build: "APP_BUILD"
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      securityContext: {}
      containers:
        - name: APP_NAME
          securityContext: {}
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 150
            initialDelaySeconds: 2
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  labels:
    name: APP_NAME
    project: PROJECT_NAME
    version: 'APP_VERSION'
    app_build: "APP_BUILD"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: APP_NAME
    project: PROJECT_NAME
---
# Virtual Service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: APP_NAME
  labels:
    name: APP_NAME
    project: PROJECT_NAME
    version: 'APP_VERSION'
    app_build: "APP_BUILD"
spec:
  hosts:
    - app.PROJECT_NAME.cilalabs.dev
  gateways:
    - istio-system/PROJECT_NAME-gateway
  http:
    - match:
        - uri:
            prefix: '/'
      route:
        - destination:
            host: APP_NAME
