variables:
  APP_NAME: app
  PROJECT_NAME: claimguru
  REPO_NAME: gitlab.com/cilalabs/$PROJECT_NAME/$APP_NAME
  GCR_REGISTRY_NAME: us-west1-docker.pkg.dev

stages:
  - build
  - deploy
  - cleanup

# This task creates image for MR review
build_review_image:
  stage: build
  image: cilalabs/git-sops
  services:
    - name: docker:18.09.9-dind
      command: ['--mtu=1460']
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
    SOPS_KMS: projects/pre-prod-286801/locations/global/keyRings/sops/cryptoKeys/sops-key
    APP_ENV: review
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_IMAGE: us-west1-docker.pkg.dev/pre-prod-286801/$PROJECT_NAME/$APP_NAME:${CI_MERGE_REQUEST_IID}
  script:
    - echo "$SERVICE_ACCOUNT_KEY" > /tmp/key.json
    - sops --kms ${SOPS_KMS} -d docker/env.$APP_ENV > .env
    - docker build -t ${DOCKER_IMAGE} .
    - docker login -u _json_key --password-stdin https://${GCR_REGISTRY_NAME} < /tmp/key.json
    - docker push ${DOCKER_IMAGE}
  tags:
    - pre-production
  only:
    - merge_requests

# This task deploys MR review set up on cluster.
review_deploy:
  stage: deploy
  image: cilalabs/kubeninja:0.0.9
  variables:
    DOCKER_IMAGE: us-west1-docker.pkg.dev/pre-prod-286801/$PROJECT_NAME/$APP_NAME:${CI_MERGE_REQUEST_IID}
    KUBE_NAMESPACE: $PROJECT_NAME-$APP_NAME-${CI_MERGE_REQUEST_IID}
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
  script:
    - echo "$SERVICE_ACCOUNT_KEY" > /tmp/key.json
    - echo $CI_MERGE_REQUEST_IID
    - kubectl version
    - kubectl create namespace ${KUBE_NAMESPACE} --dry-run -o yaml | kubectl apply -f -
    - kubectl label namespace ${KUBE_NAMESPACE} istio-injection=enabled --dry-run -o yaml | kubectl apply -f -
    - sed -i "s/CI_COMMIT_SHORT_SHA/${CI_COMMIT_SHORT_SHA}/g" k8s/review/crd-spec.yaml
    - sed -i "s/CI_MERGE_REQUEST_IID/${CI_MERGE_REQUEST_IID}/g" k8s/review/crd-spec.yaml
    - sed -i "s~DOCKER_IMAGE~${DOCKER_IMAGE}~g" k8s/review/crd-spec.yaml
    - sed -i "s/CI_JOB_ID/${CI_JOB_ID}/g" k8s/review/crd-spec.yaml
    - kubectl apply -f k8s/review/crd-spec.yaml --namespace ${KUBE_NAMESPACE}
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://app-${CI_MERGE_REQUEST_IID}.$PROJECT_NAME.cilalabs.dev
    on_stop: review_cleanup
  tags:
    - pre-production
  only:
    - merge_requests

# This task cleans up MR review set up.
review_cleanup:
  stage: cleanup
  needs:
    - review_deploy
  image: cilalabs/kubeninja:0.0.9
  variables:
    KUBE_NAMESPACE: $PROJECT_NAME-$APP_NAME-${CI_MERGE_REQUEST_IID}
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  script:
    - kubectl version
    - kubectl delete namespace ${KUBE_NAMESPACE}
  when: manual
  tags:
    - pre-production
  only:
    - merge_requests

# This task creates master image.
build_master_image:
  stage: build
  image: cilalabs/git-sops
  services:
    - name: docker:18.09.9-dind
      command: ['--mtu=1460']
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
    SOPS_KMS: projects/pre-prod-286801/locations/global/keyRings/sops/cryptoKeys/sops-key
    APP_ENV: dev
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_IMAGE: us-west1-docker.pkg.dev/pre-prod-286801/$PROJECT_NAME/$APP_NAME
  script:
    - echo "$SERVICE_ACCOUNT_KEY" > /tmp/key.json
    - sops --kms ${SOPS_KMS} -d docker/env.$APP_ENV > .env
    - docker build -t ${DOCKER_IMAGE} .
    - docker login -u _json_key --password-stdin https://${GCR_REGISTRY_NAME} < /tmp/key.json
    - docker push ${DOCKER_IMAGE}
  tags:
    - pre-production
  only:
    - master

# This task deploy pre production set up.
dev_deploy:
  stage: deploy
  image: cilalabs/kubeninja:0.0.9
  variables:
    DOCKER_IMAGE: us-west1-docker.pkg.dev/pre-prod-286801/$PROJECT_NAME/$APP_NAME
    KUBE_NAMESPACE: $PROJECT_NAME
    APP_ENVIRONMENT: dev
    APP_VERSION: $CI_COMMIT_SHORT_SHA
    APP_BUILD: $CI_JOB_ID
  script:
    - deploy frontend
    - kubectl rollout status deployment $APP_NAME --namespace ${KUBE_NAMESPACE} --watch --timeout=10m
  environment:
    name: pre-production
    url: https://app.$PROJECT_NAME.cilalabs.dev
  tags:
    - pre-production
  only:
    - master

# This task creates image associated with tag for staging env
build_tag_image_stage:
  stage: build
  image: cilalabs/git-sops
  services:
    - name: docker:18.09.9-dind
      command: ['--mtu=1460']
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
    SOPS_KMS: projects/pre-prod-286801/locations/global/keyRings/sops/cryptoKeys/sops-key
    APP_ENV: stage
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_IMAGE: us-west1-docker.pkg.dev/pre-prod-286801/$PROJECT_NAME/$APP_NAME-stage:${CI_COMMIT_TAG}
  script:
    - echo "$SERVICE_ACCOUNT_KEY"  > /tmp/key.json
    - sops --kms ${SOPS_KMS} -d docker/env.$APP_ENV > .env
    - docker build -t ${DOCKER_IMAGE} .
    - docker login -u _json_key --password-stdin https://${GCR_REGISTRY_NAME} < /tmp/key.json
    - docker push ${DOCKER_IMAGE}
  tags:
    - pre-production
  only:
    - tags


# This task deploy set up to staging env.
stage_deploy:
  stage: deploy
  image: cilalabs/kubeninja:0.0.9
  variables:
    KUBE_NAMESPACE: $PROJECT_NAME-stage
    DOCKER_IMAGE: us-west1-docker.pkg.dev/pre-prod-286801/$PROJECT_NAME/$APP_NAME-stage:${CI_COMMIT_TAG}
    APP_ENVIRONMENT: stage
    APP_VERSION: $CI_COMMIT_TAG
    APP_BUILD: $CI_JOB_ID
  script:
    - deploy frontend
    - kubectl rollout status deployment $APP_NAME --namespace ${KUBE_NAMESPACE} --watch --timeout=10m
  environment:
    name: staging
    url: https://app.stage.$PROJECT_NAME.com
  tags:
    - pre-production
  only:
    - tags

# This task creates image associated with tag for prod env
build_tag_image_prod:
  stage: build
  image: cilalabs/git-sops
  services:
    - name: docker:18.09.9-dind
      command: ['--mtu=1460']
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
    SOPS_KMS: projects/prod-286801/locations/global/keyRings/sops/cryptoKeys/sops-key
    APP_ENV: production
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_IMAGE: us-west1-docker.pkg.dev/pre-prod-286801/$PROJECT_NAME/$APP_NAME:${CI_COMMIT_TAG}
  script:
    - echo "$DEPLOY_SA_KEY"  > /tmp/key.json
    - sops --kms ${SOPS_KMS} -d docker/env.$APP_ENV > .env
    - docker build -t ${DOCKER_IMAGE} .
    - docker login -u _json_key --password-stdin https://${GCR_REGISTRY_NAME} < /tmp/key.json
    - docker push ${DOCKER_IMAGE}
  tags:
    - prod-shared
  only:
    - tags
  when: manual

# This task deploy production set up.
prod_deploy:
  stage: deploy
  image: cilalabs/kubeninja:0.0.9
  variables:
    KUBE_NAMESPACE: $PROJECT_NAME
    DOCKER_IMAGE: us-west1-docker.pkg.dev/pre-prod-286801/$PROJECT_NAME/$APP_NAME:${CI_COMMIT_TAG}
    APP_ENVIRONMENT: prod
    APP_VERSION: $CI_COMMIT_TAG
    APP_BUILD: $CI_JOB_ID
  script:
    - deploy frontend
    - kubectl rollout status deployment $APP_NAME --namespace ${KUBE_NAMESPACE} --watch --timeout=5m
  environment:
    name: production
    url: https://$PROJECT_NAME.com
  tags:
    - prod-shared
  only:
    - tags
  when: manual
