image: alpine:latest

variables:
  REPO_NAME: gitlab.com/cilalabs/claimguru/claimguru-ui
  DOCKER_REGISTRY: us-west1-docker.pkg.dev

stages:
  - test
  - build
  - deploy
  - cleanup

# This task creates image for MR review
build_review_image:
  stage: build
  image: docker:git
  services:
    - docker:18.09.9-dind
  variables:
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_IMAGE: us-west1-docker.pkg.dev/pre-prod-286801/claimguru/claimguru-ui:${CI_MERGE_REQUEST_ID}
  script:
    - cp $env_review .env
    - docker build -t ${DOCKER_IMAGE} .
    - echo "$SERVICE_ACCOUNT_KEY" > key.json
    - docker login -u _json_key --password-stdin https://${DOCKER_REGISTRY} < key.json
    - docker push ${DOCKER_IMAGE}
  tags:
    - pre-production
  only:
    - merge_requests

# This task deploys MR review set up on cluster.
review_deploy:
  stage: deploy
  image:
    name: us-west1-docker.pkg.dev/pre-prod-286801/cilalabs/common-utils/kubeninja
  variables:
    DOCKER_IMAGE: us-west1-docker.pkg.dev/pre-prod-286801/claimguru/claimguru-ui:${CI_MERGE_REQUEST_ID}
    KUBE_NAMESPACE: claimguru-ui-${CI_MERGE_REQUEST_ID}
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
    SOPS_KMS: projects/pre-prod-286801/locations/global/keyRings/sops/cryptoKeys/sops-key
  script:
    - echo "$SERVICE_ACCOUNT_KEY" > /tmp/key.json
    - echo $CI_MERGE_REQUEST_ID
    - kubectl version
    - kubectl create namespace ${KUBE_NAMESPACE} --dry-run -o yaml | kubectl apply -f -
    - kubectl label namespace ${KUBE_NAMESPACE} istio-injection=enabled --dry-run -o yaml | kubectl apply -f -
    - kubectl create secret generic app-sa-key --from-file /tmp/key.json --namespace ${KUBE_NAMESPACE} --dry-run -o yaml | kubectl apply -f -
    - kubectl apply -f k8s/dev/values.yaml --namespace ${KUBE_NAMESPACE}
    - sed -i "s/CI_COMMIT_SHORT_SHA/${CI_COMMIT_SHORT_SHA}/g" k8s/dev/crd-spec.yaml
    - sed -i "s/CI_MERGE_REQUEST_ID/${CI_MERGE_REQUEST_ID}/g" k8s/dev/crd-spec.yaml
    - sed -i "s~DOCKER_IMAGE~${DOCKER_IMAGE}~g" k8s/dev/crd-spec.yaml
    - kubectl apply -f k8s/dev/crd-spec.yaml --namespace ${KUBE_NAMESPACE}
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://claimguru-ui-${CI_MERGE_REQUEST_ID}.claimguru.cilalabs.dev
    on_stop: review_cleanup
  tags:
    - pre-production
  only:
    - merge_requests

# This task cleans up MR review set up.
review_cleanup:
  stage: cleanup
  image:
    name: us-west1-docker.pkg.dev/pre-prod-286801/cilalabs/common-utils/kubeninja
  variables:
    KUBE_NAMESPACE: claimguru-ui-${CI_MERGE_REQUEST_ID}
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  script:
    - kubectl version
    - kubectl delete namespace ${KUBE_NAMESPACE}
  when: manual
  tags:
    - pre-production
  only:
    - merge_requests

# This task creates master image.
build_master_image:
  stage: build
  image: docker:git
  services:
    - docker:18.09.9-dind
  variables:
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_IMAGE: us-west1-docker.pkg.dev/pre-prod-286801/claimguru/claimguru-ui
  script:
    - cp $env_pre_prod .env
    - docker build -t ${DOCKER_IMAGE} .
    - echo "$SERVICE_ACCOUNT_KEY" > key.json
    - docker login -u _json_key --password-stdin https://${DOCKER_REGISTRY} < key.json
    - docker push ${DOCKER_IMAGE}
  tags:
    - pre-production
  only:
    - master

# This task deploy pre production set up.
pre_prod_deploy:
  stage: deploy
  image:
    name: us-west1-docker.pkg.dev/pre-prod-286801/cilalabs/common-utils/kubeninja
  variables:
    DOCKER_IMAGE: us-west1-docker.pkg.dev/pre-prod-286801/claimguru/claimguru-ui
    KUBE_NAMESPACE: claimguru
    GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
    SOPS_KMS: projects/pre-prod-286801/locations/global/keyRings/sops/cryptoKeys/sops-key
  script:
    - echo "$SERVICE_ACCOUNT_KEY" > /tmp/key.json
    - kubectl version
    - kubectl create namespace ${KUBE_NAMESPACE} --dry-run -o yaml | kubectl apply -f -
    - kubectl label namespace ${KUBE_NAMESPACE} istio-injection=enabled --dry-run -o yaml | kubectl apply -f -
    - kubectl create secret generic app-sa-key --from-file /tmp/key.json --namespace ${KUBE_NAMESPACE} --dry-run -o yaml | kubectl apply -f - 
    - kubectl apply -f k8s/pre-prod/values.yaml --namespace ${KUBE_NAMESPACE}
    - sed -i "s/CI_COMMIT_SHORT_SHA/${CI_COMMIT_SHORT_SHA}/g" k8s/pre-prod/crd-spec.yaml
    - sed -i "s~DOCKER_IMAGE~${DOCKER_IMAGE}~g" k8s/pre-prod/crd-spec.yaml
    - kubectl apply -f k8s/pre-prod/crd-spec.yaml --namespace ${KUBE_NAMESPACE}
  environment:
    name: pre-production
    url: https://claimguru.cilalabs.dev
  tags:
    - pre-production
  only:
    - master
