export const clients = state => state.clients;
export const estimators = state => state.estimators;
export const clientTypes = state => state.clientTypes;
export const propertyTypes = state => state.propertyTypes;
export const claimReasons = state => state.claimReasons;
export const lossCauses = state => state.lossCauses;
export const claimSeverity = state => state.claimSeverity;
export const policyCategories = state => state.policyCategories;
export const policyTypes = state => state.policyTypes;
