export default function() {
  return {
    claims: [],
    claim: {},
    log: [],
    claimNotes: [],
    personnel: [],
    account: [],
    payment: [],
    expenses: [],
    disbursements: [],
    policy: [],
    lossInfo: [],
    settlementType: [],
    settlement: [],
    claimTasks: [],
    mortgage: [],
    vendorLists: [],
    phases: [],
    damageInfo: [],
    tasks: [],
    templateOptions: [],
    claimDocument: [],
    vendorDocument: [],
    claimStatic: {},
    claimPhoto: [],
    claimSketch: [],
    additionalDocs: [],
    esxDocs: [],
    proofOfLoss: {},
    estimator: {},
    claimPOLDocument: {},
    actors: [],
    signedContractDocument: ''
  };
}
